name: Bionify les classiques

on: 
  workflow_dispatch:

jobs:
  classiques-bioniques:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: update repo
      run: |
        git submodule update --init --recursive
        
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: 3.x

    - name: install dependencies
      run: |
        if [ -f ./scripts/requirements.txt ]; then pip3 install -r ./scripts/requirements.txt; fi

    - name: run the script
      run: |
        python3 ./bionic-converter.py

    - name: compress e-books
      run: |
        zip -r classiques-bioniques.zip out/ -i '*.epub'
        
    - uses: actions/upload-artifact@master
      with:
        name: classiques-bioniques
        path: classiques-bioniques.zip