name: Bionify les classiques

on: 
  workflow_dispatch:

jobs:
  classiques-bioniques:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: 3.x

    - name: install dependencies
      run: |
        if [ -f ./requirements.txt ]; then pip3 install -r ./requirements.txt; fi
        sudo apt-get install pandoc

    - name: run the script
      run: |
        python3 ./bionic-converter.py

    - uses: actions/upload-artifact@master
      with:
        name: classiques-bioniques
        path: out/*.epub